/** Renderer-independent slice contract. All money is integer cents. x/z are metres. */
export type RecipeId = 'espresso' | 'latte';
export type CounterId = 'counter-a' | 'counter-b';
export type CustomerPhase = 'entering' | 'queue' | 'serving' | 'receiving' | 'leaving';
export interface Brew { recipe: RecipeId; elapsed: number; duration: number; price: number; customerId: number }
export interface Counter { id: CounterId; x: number; level: number; recipe: RecipeId; pendingCash: number; brewed: number; brew: Brew | null }
export interface Customer { id: number; x: number; z: number; phase: CustomerPhase; counterId: CounterId; timer: number; hasCup: boolean; skin: number; /** Next waypoint on the current separated customer route. */ routeLeg?: 0 | 1 | 2 | 3; /** Complete only an already-moving pre-v2 customer leg without teleporting. */ finishLegacyRoute?: true }
export interface Manager { x: number; z: number; carrying: number; phase: 'moving' | 'collecting' | 'depositing'; /** Counter array index, or 2 for the vault. */ target: number; timer: number; level: number; /** Finish only the uncompleted stops of a migrated A-first sweep, then remove at deposit. */ finishLegacySweep?: true }
export interface SliceState { schemaVersion: 1; economyVersion: 1; /** Missing/1 is the previous A-first route with vault x=-8; 2 uses shared world coordinates and B-first sweeps. */ managerRouteVersion?: 1 | 2; /** Missing/1 has shared entry/exit traffic; 2 has local exits; 3 extends them along a parallel return lane to the entrance-side boundary. */ customerRouteVersion?: 1 | 2 | 3; elapsed: number; wallet: number; totalEarned: number; totalServed: number; spend: number; nextCustomerId: number; arrivalTimer: number; inviteCooldown: number; paused: boolean; counters: Counter[]; customers: Customer[]; manager: Manager; lastOfflineClaimId: string | null; /** Persist fractional fixed-step time instead of throwing it away per frame. */ stepCarry?: number; /** Monotonic event IDs survive a save/reload. */ eventSequence?: number; /** Recent operation replay protection; the repository's savedAt is the interval authority. */ offlineClaimIds?: string[] }
export interface Recipe { id: RecipeId; name: string; price: number; brewSeconds: number; color: string; description: string }
export interface CounterQuote { cost: number; beforePrice: number; afterPrice: number; beforeSeconds: number; afterSeconds: number; paybackSeconds: number; capped: boolean }
export interface SliceEvent { id: number; type: 'arrived' | 'brewed' | 'served' | 'collected' | 'deposited' | 'upgraded' | 'recipe-changed' | 'invited'; amount?: number; counterId?: CounterId }
export type OfflinePolicyVersion = 1 | 2 | 3;
export interface OfflineResult { accepted: boolean; amount: number; seconds: number; effectiveSeconds?: number; awaySeconds?: number; policyVersion?: OfflinePolicyVersion; generatedAmount?: number; pendingCash?: number; carrying?: number }
/** A detached engine owns a single exact claim; batches never apply efficiency twice. */
export interface OfflineJob { readonly accepted: boolean; readonly done: boolean; readonly totalSeconds: number; readonly completedSeconds: number; advance(maxSteps: number): void; result(): OfflineResult }
export interface SliceEngine { readonly state: SliceState; advance(seconds: number, beforeLastStep?: (state: Readonly<SliceState>) => void): void; invite(): boolean; upgrade(id: CounterId): boolean; upgradeManager(): boolean; setRecipe(id: CounterId, recipe: RecipeId): boolean; togglePause(): void; quote(id: CounterId): CounterQuote; managerQuote(): { cost: number; speed: number; nextSpeed: number; capped: boolean }; drainEvents(): SliceEvent[]; snapshot(): SliceState; beginOffline(seconds: number, claimId: string, policy?: OfflinePolicyVersion): OfflineJob; applyOffline(seconds: number, claimId: string, policy?: OfflinePolicyVersion): OfflineResult }
