/** Renderer-independent slice contract. All money is integer cents. x/z are metres; layout origins are integer tile centres. */
export type RecipeId = 'espresso' | 'latte';
export type IngredientId = 'beans' | 'milk';
export type PurchaseMode = 'one' | 'batch' | 'fill';
export interface IngredientStock { beans: number; milk: number }
export interface IngredientQuote { quantity: number; cost: number; stock: number; capacity: number; affordable: boolean }
export type CounterId = 'counter-a' | 'counter-b' | 'counter-c' | 'counter-d';
export type CustomerPhase = 'entering' | 'queue' | 'serving' | 'receiving' | 'seeking-seat' | 'dining' | 'leaving';
export interface Brew { recipe: RecipeId; elapsed: number; duration: number; price: number; customerId: number }
export interface Counter { id: CounterId; x: number; level: number; recipe: RecipeId; pendingCash: number; brewed: number; brew: Brew | null }
export interface Customer { id: number; x: number; z: number; phase: CustomerPhase; counterId: CounterId; timer: number; hasCup: boolean; /** Only unstarted orders may leave empty when stock is unavailable. */ departureReason?: 'stockout'; skin: number; seatId?: string; nav?: GridPoint[]; /** Next waypoint on the current separated customer route. */ routeLeg?: 0 | 1 | 2 | 3; /** Complete only an already-moving pre-v2 customer leg without teleporting. */ finishLegacyRoute?: true }
export interface Manager { x: number; z: number; carrying: number; phase: 'moving' | 'collecting' | 'depositing'; /** Counter array index; counters.length is the vault (2 on legacy routes). */ target: number; collectionCursor?: number; nav?: GridPoint[]; timer: number; level: number; /** Finish only the uncompleted stops of a migrated A-first sweep, then remove at deposit. */ finishLegacySweep?: true }
export interface SliceState { schemaVersion: 1; economyVersion: 5; ingredients: IngredientStock; layout?: ShopLayout; /** One-time visible notice when old exit-blocking furniture was stored/repositioned. */ doorMigrationNotice?: true; /** Shared recipe progression, independent of each counter's level. */ coffeeLevels: Record<RecipeId, number>; /** Missing/1 is the previous A-first route with vault x=-8; 2 uses shared world coordinates and B-first sweeps. */ managerRouteVersion?: 1 | 2; /** 1–3 are legacy traffic retained only until in-flight guests drain; 4 uses opposite doors. */ customerRouteVersion?: 1 | 2 | 3 | 4; elapsed: number; wallet: number; totalEarned: number; totalServed: number; spend: number; nextCustomerId: number; arrivalTimer: number; inviteCooldown: number; /** Business closed: no new guests; existing guests may finish online. */ paused: boolean; counters: Counter[]; customers: Customer[]; manager: Manager; lastOfflineClaimId: string | null; /** Persist fractional fixed-step time instead of throwing it away per frame. */ stepCarry?: number; /** Monotonic event IDs survive a save/reload. */ eventSequence?: number; /** Recent operation replay protection; the repository's savedAt is the interval authority. */ offlineClaimIds?: string[] }
export interface Recipe { id: RecipeId; name: string; price: number; brewSeconds: number; color: string; description: string }
export interface CounterQuote { cost: number; beforePrice: number; afterPrice: number; beforeSeconds: number; afterSeconds: number; paybackSeconds: number; capped: boolean }
export interface CoffeeQuote { level: number; nextLevel: number; cost: number; beforePrice: number; afterPrice: number; beforeSeconds: number; afterSeconds: number; capped: boolean }
export interface SliceEvent { id: number; type: 'arrived' | 'brewed' | 'served' | 'collected' | 'deposited' | 'upgraded' | 'coffee-upgraded' | 'recipe-changed' | 'invited' | 'layout-changed' | 'ingredients-purchased'; amount?: number; counterId?: CounterId; recipeId?: RecipeId; ingredientId?: IngredientId }
export type OfflinePolicyVersion = 1 | 2 | 3 | 4;
export interface OfflineResult { accepted: boolean; amount: number; seconds: number; effectiveSeconds?: number; awaySeconds?: number; policyVersion?: OfflinePolicyVersion; generatedAmount?: number; pendingCash?: number; carrying?: number; stockout?: boolean }
/** A detached engine owns a single exact claim; batches never apply efficiency twice. */
export interface OfflineJob { readonly accepted: boolean; readonly done: boolean; readonly totalSeconds: number; readonly completedSeconds: number; advance(maxSteps: number): void; result(): OfflineResult }
export interface SliceEngine { readonly state: SliceState; ingredientQuote(id: IngredientId, mode: PurchaseMode): IngredientQuote; buyIngredient(id: IngredientId, mode: PurchaseMode): boolean; beginLayoutEdit(): boolean; layoutEditStatus(): 'idle' | 'draining' | 'ready'; createLayoutDraft(): ShopLayout | null; commitLayout(draft: ShopLayout): LayoutResult; cancelLayoutEdit(): void; advance(seconds: number, beforeLastStep?: (state: Readonly<SliceState>) => void): void; invite(): boolean; upgrade(id: CounterId): boolean; upgradeManager(): boolean; upgradeCoffee(recipe: RecipeId): boolean; coffeeQuote(recipe: RecipeId): CoffeeQuote; setRecipe(id: CounterId, recipe: RecipeId): boolean; togglePause(): void; quote(id: CounterId): CounterQuote; managerQuote(): { cost: number; speed: number; nextSpeed: number; capped: boolean }; drainEvents(): SliceEvent[]; snapshot(): SliceState; beginOffline(seconds: number, claimId: string, policy?: OfflinePolicyVersion): OfflineJob; applyOffline(seconds: number, claimId: string, policy?: OfflinePolicyVersion): OfflineResult }

export interface GridPoint { x: number; z: number }
export interface FurniturePlacement extends GridPoint { id: string; kind: 'counter' | 'table'; rotation: 0 | 1 | 2 | 3; stored: boolean; counterId?: CounterId }
export type CoffeeSignId = 'menu-espresso' | 'menu-latte';
/** A wall menu represents a globally owned recipe; storing it never disables that recipe. */
export interface CoffeeSignPlacement { id: CoffeeSignId; recipe: RecipeId; x: number; stored: boolean }
export interface ShopLayout { version: 2 | 3; active: boolean; expanded: boolean; furniture: FurniturePlacement[]; coffeeSigns: CoffeeSignPlacement[]; trafficTurn?: 'customer' | 'manager' }
export interface LayoutResult { ok: boolean; message: string; cost?: number }
