import test from 'node:test';
import assert from 'node:assert/strict';
import {registerHooks} from 'node:module';
import {DatabaseSync} from 'node:sqlite';
import {readFileSync,readdirSync} from 'node:fs';
registerHooks({resolve(s,c,next){try{return next(s,c);}catch(e){if(s.startsWith('.')&&!/\.[a-z]+$/i.test(s))return next(s+'.ts',c);throw e;}}});
const {api}=await import('../worker/index.ts');
const worker=(await import('../worker/index.ts')).default;
const {createInitialState}=await import('../src/slice/core/engine.ts');
const {LocalSaveRepository,createMemoryStorage,SAVE_KEY,decode}=await import('../src/slice/core/persistence.ts');
const {ManualSync,MANUAL_PREFIX}=await import('../src/cloud/manual.ts');
class MemoryStorage {m=new Map();get length(){return this.m.size;}key(i){return [...this.m.keys()][i]??null;}getItem(k){return this.m.get(k)??null;}setItem(k,v){this.m.set(k,String(v));}removeItem(k){this.m.delete(k);}}
class D1 {
 db=new DatabaseSync(':memory:');fail=false;
 constructor(){for(const f of readdirSync(new URL('../drizzle/',import.meta.url)).filter(x=>x.endsWith('.sql')).sort())this.db.exec(readFileSync(new URL('../drizzle/'+f,import.meta.url),'utf8'));}
 prepare(sql){let args=[];const self=this;return{bind(...v){args=v;return this;},async first(){return self.db.prepare(sql).get(...args)??null;},async all(){return {results:self.db.prepare(sql).all(...args)};},async run(){return{success:true,meta:self.db.prepare(sql).run(...args)};}};}
 async batch(list){this.db.exec('BEGIN');try{const result=[];for(const[i,q]of list.entries()){result.push(await q.run());if(this.fail&&i===0)throw Error('synthetic rollback');}this.db.exec('COMMIT');return result;}catch(e){this.db.exec('ROLLBACK');throw e;}}
}
const user='synthetic-user-a',other='synthetic-user-b',uuid=()=>crypto.randomUUID();
function raw(state=createInitialState(),now=100000){const store=createMemoryStorage(),repo=new LocalSaveRepository(store);repo.load(now);assert.equal(repo.save(state,now).ok,true);return store.getItem(SAVE_KEY);}
async function call(db,path,body,who=user,now=Date.now(),origin='https://coffee.test'){const r=await api(new Request('https://coffee.test'+path,{method:body===undefined?'GET':'POST',headers:{...(who?{'oai-authenticated-user-id':who}:{}),'Content-Type':'application/json',Origin:origin},body:body===undefined?undefined:JSON.stringify({...body,expectedUser:body.expectedUser??who})}),{DB:db},now);return{status:r.status,...await r.json()};}

const op=(snapshot=raw(),revision=0)=>({protocol:3,revision,raw:snapshot,opId:uuid()});
const state=r=>JSON.parse(r.raw).state;
function wiring(db,who=user){let calls=[],drop=false;globalThis.fetch=async(path,options={})=>{calls.push({path,method:options.method??'GET',body:options.body});const result=await call(db,path,options.body?JSON.parse(options.body):undefined,who);if(drop&&options.body){drop=false;throw Error('lost ACK');}return new Response(JSON.stringify(result),{status:result.status});};return{calls,loseNextAck(){drop=true;}};}
test('MANUAL-001 authenticated owner isolation, same-origin and expected-user checks',async()=>{
 const db=new D1();assert.equal((await call(db,'/api/save',undefined,null)).status,401);assert.equal((await call(db,'/api/save',op(),user,Date.now(),'https://evil.test')).status,403);assert.equal((await call(db,'/api/save',{...op(),expectedUser:other})).status,401);assert.equal((await call(db,'/api/save',op())).status,200);assert.equal((await call(db,'/api/save',undefined,other)).raw,null);assert.equal((await call(db,'/api/backups',undefined,other)).backups.length,0);
});
test('MANUAL-002 reads never advance clock or revision; old authority endpoints are permanently retired',async()=>{
 const db=new D1(),first=await call(db,'/api/save',op());const before=db.db.prepare('SELECT * FROM coffee_saves').get();for(const path of ['/api/command','/api/session']){assert.equal((await call(db,path,{command:{type:'upgrade-coffee'},raw:raw()})).status,410);assert.equal((await call(db,path)).status,410);}const later=await call(db,'/api/save',undefined,user,9999999999999);assert.equal(later.raw,first.raw);assert.deepEqual(db.db.prepare('SELECT * FROM coffee_saves').get(),before);
});
test('MANUAL-003 CAS protects concurrent devices and exact lost-ACK replay cannot overwrite successors',async()=>{
 const db=new D1(),a=op(),first=await call(db,'/api/save',a);const s=createInitialState();s.wallet+=123;s.totalEarned+=123;const b=op(raw(s),1),second=await call(db,'/api/save',b);assert.equal(second.revision,2);assert.equal((await call(db,'/api/save',op(raw(),1))).status,409);const replay=await call(db,'/api/save',a);assert.equal(replay.acceptedRevision,1);assert.equal(replay.replayed,true);assert.equal(replay.raw,second.raw);assert.equal((await call(db,'/api/save',{...a,raw:raw(s)})).status,400);assert.equal(db.db.prepare('SELECT COUNT(*) AS n FROM coffee_operations').get().n,2);assert.equal((await call(db,'/api/backups')).backups[0].raw,first.raw);
});
test('MANUAL-004 failed D1 transaction preserves snapshot, receipt and backup atomically',async()=>{
 const db=new D1(),first=await call(db,'/api/save',op());db.fail=true;await assert.rejects(call(db,'/api/save',op(raw(),1)));db.fail=false;assert.equal((await call(db,'/api/save')).raw,first.raw);assert.equal(db.db.prepare('SELECT COUNT(*) AS n FROM coffee_operations').get().n,1);assert.equal((await call(db,'/api/backups')).backups.length,0);
});
test('MANUAL-005 rejects malformed, future-version and legacy protocol writes',async()=>{
 const db=new D1();assert.equal((await call(db,'/api/save',{...op(),protocol:2})).status,400);assert.equal((await call(db,'/api/save',{...op(),wallet:999999})).status,400);assert.equal((await call(db,'/api/save',op('{}'))).status,422);const e=JSON.parse(raw());e.state.economyVersion=10;assert.equal((await call(db,'/api/save',op(JSON.stringify(e)))).status,422);const future=JSON.parse(raw());future.savedAt=Date.now()+9999999;assert.equal((await call(db,'/api/save',op(JSON.stringify(future)))).status,422);
});
test('MANUAL-006 document carries only trusted identity; startup rendering never reads D1',async()=>{
 let queries=0;const response=await worker.fetch(new Request('https://coffee.test/',{headers:{'oai-authenticated-user-id':'synthetic"><tag'}}),{DB:{prepare(){queries++;throw Error('unexpected DB');}},ASSETS:{async fetch(){return new Response('<html><head><title>Shop</title></head><body></body></html>',{headers:{'Content-Type':'text/html','ETag':'old'}});}}});assert.equal(queries,0);assert.match(await response.text(),/content="synthetic%22%3E%3Ctag"/);assert.match(response.headers.get('Cache-Control'),/no-store/);assert.equal(response.headers.get('ETag'),null);assert.equal((await worker.fetch(new Request('https://coffee.test/'),{})).status,302);
});
test('MANUAL-007 constructor/local autosave/offline/online events make zero requests',async()=>{
 const before=globalThis.fetch;let requests=0;globalThis.fetch=async()=>{requests++;throw Error('no network allowed');};try{const local=new MemoryStorage(),client=new ManualSync(user,local),repo=new LocalSaveRepository(client.storage());repo.load(100000);repo.save(createInitialState(),100000);repo.load(400000);client.storage().setItem('preference','x');await new Promise(r=>setTimeout(r,20));assert.equal(requests,0);assert.ok(client.branch.raw);const bootstrap=readFileSync(new URL('../src/cloud/bootstrap.ts',import.meta.url),'utf8'),manual=readFileSync(new URL('../src/cloud/manual.ts',import.meta.url),'utf8');assert.doesNotMatch(manual,/setInterval|setTimeout|addEventListener/);assert.doesNotMatch(bootstrap,/new AuthorityClient|new CloudSync|\.connect\(/);}finally{globalThis.fetch=before;}
});
test('MANUAL-008 one click uploads current snapshot, duplicate clicks single-flight, next local saves stay local',async()=>{
 const before=globalThis.fetch;try{const db=new D1(),net=wiring(db),client=new ManualSync(user,new MemoryStorage());client.storage().setItem(SAVE_KEY,raw());await Promise.all([client.sync(),client.sync(),client.sync()]);assert.equal(net.calls.length,2);assert.equal(client.branch.baseRevision,1);client.storage().setItem(SAVE_KEY,raw(createInitialState(),200000));assert.equal(net.calls.length,2);assert.equal((await call(db,'/api/save')).raw,client.branch.baseRaw);}finally{globalThis.fetch=before;}
});
test('MANUAL-009 unknown first cloud and divergent revisions always require explicit choice',async()=>{
 const before=globalThis.fetch;try{const db=new D1(),first=await call(db,'/api/save',op()),net=wiring(db),client=new ManualSync(user,new MemoryStorage());const s=createInitialState();s.wallet+=900;s.totalEarned+=900;client.storage().setItem(SAVE_KEY,raw(s));let choices=0;client.onChoice=async()=>{choices++;return 'cancel';};await client.sync();assert.equal(choices,1);assert.equal(net.calls.length,1);assert.equal((await call(db,'/api/save')).raw,first.raw);assert.equal(JSON.parse(client.branch.raw).state.wallet,s.wallet);}finally{globalThis.fetch=before;}
});
test('MANUAL-010 conflict upload backs up both snapshots and retries changed cloud only after another choice',async()=>{
 const before=globalThis.fetch;try{const db=new D1(),original=await call(db,'/api/save',op()),local=new MemoryStorage(),client=new ManualSync(user,local);wiring(db);const s=createInitialState();s.wallet+=50;s.totalEarned+=50;const own=raw(s);client.storage().setItem(SAVE_KEY,own);let choices=0;client.onChoice=async cloud=>{choices++;if(choices===1)await call(db,'/api/save',op(raw(createInitialState(),200000),cloud.revision));return 'upload';};await client.sync();assert.equal(choices,2);assert.equal((await call(db,'/api/save')).raw,own);const backups=[...local.m.values()].map(x=>{try{return JSON.parse(x);}catch{return{};}}).filter(x=>x.label);assert.ok(backups.some(x=>x.raw===own));assert.ok(backups.some(x=>x.raw===original.raw));}finally{globalThis.fetch=before;}
});
test('MANUAL-011 lost response persists exact pending op and replay never loses later local progress',async()=>{
 const before=globalThis.fetch;try{const db=new D1(),local=new MemoryStorage(),client=new ManualSync(user,local),net=wiring(db);client.storage().setItem(SAVE_KEY,raw());net.loseNextAck();await client.sync();assert.ok(client.branch.pending);const pending=structuredClone(client.branch.pending);const s=createInitialState();s.wallet+=99;s.totalEarned+=99;client.storage().setItem(SAVE_KEY,raw(s));const reopened=new ManualSync(user,local);assert.equal(reopened.branch.pending.opId,pending.opId);await reopened.sync();assert.equal(reopened.branch.pending,null);assert.equal(state(await call(db,'/api/save')).wallet,s.wallet);assert.equal((await call(db,'/api/save')).revision,2);assert.equal(JSON.parse(net.calls[2].body).opId,pending.opId);}finally{globalThis.fetch=before;}
});
test('MANUAL-012 explicit download reanchors without old-file income, repeated download does not duplicate money',async()=>{
 const before=globalThis.fetch;try{const db=new D1(),cloud=await call(db,'/api/save',op(raw(createInitialState(),1000))),client=new ManualSync(user,new MemoryStorage());wiring(db);client.storage().setItem(SAVE_KEY,raw());client.onChoice=async()=> 'download';let adopted=0;client.onAdopt=()=>adopted++;await client.sync('download');const first=decode(client.branch.raw).envelope;assert.equal(first.state.wallet,state(cloud).wallet);assert.ok(first.savedAt>Date.now()-2000);await client.sync('download');assert.equal(decode(client.branch.raw).envelope.state.wallet,first.state.wallet);assert.equal(adopted,2);assert.equal((await call(db,'/api/save')).revision,1);}finally{globalThis.fetch=before;}
});
test('MANUAL-013 account switch cannot send old local progress to another owner',async()=>{
 const before=globalThis.fetch;try{const db=new D1(),local=new MemoryStorage(),client=new ManualSync(user,local);client.storage().setItem(SAVE_KEY,raw());wiring(db,other);let message='';client.onMessage=x=>message=x;await client.sync();assert.match(message,/账户已变化/);assert.equal((await call(db,'/api/save',undefined,other)).raw,null);assert.equal(new ManualSync(other,local).branch.raw,null);assert.ok(client.branch.raw);}finally{globalThis.fetch=before;}
});
test('MANUAL-014 authoritative migration uses confirmed durable raw only and never requests cloud',()=>{
 const local=new MemoryStorage(),legacy=JSON.parse(raw());legacy.state.economyVersion=6;legacy.state.coffeeLevels.latte=4;const confirmed=JSON.stringify(legacy);local.setItem('mellow-bean:authority:v2:'+encodeURIComponent(user)+':confirmed',confirmed);local.setItem('mellow-bean:authority:v2:'+encodeURIComponent(user)+':prediction','invalid prediction');const client=new ManualSync(user,local);assert.equal(client.branch.raw,confirmed);assert.equal(client.branch.baseRevision,null);assert.equal(local.getItem('mellow-bean:authority:v2:'+encodeURIComponent(user)+':confirmed'),confirmed);
});
test('MANUAL-015 backup failure aborts replacement and keeps both originals',async()=>{
 const before=globalThis.fetch;try{const db=new D1(),cloud=await call(db,'/api/save',op()),local=new MemoryStorage(),client=new ManualSync(user,local);wiring(db);const own=raw(createInitialState(),200000);client.storage().setItem(SAVE_KEY,own);client.onChoice=async()=> 'download';const set=local.setItem.bind(local);local.setItem=(key,value)=>{if(key.includes('backup:'))throw Error('quota');set(key,value);};await client.sync('download');assert.equal(client.branch.raw,own);assert.equal((await call(db,'/api/save')).raw,cloud.raw);}finally{globalThis.fetch=before;}
});

test('MANUAL-016 external branch corruption blocks local CAS instead of clobbering it',()=>{const local=new MemoryStorage(),client=new ManualSync(user,local);client.storage().setItem(SAVE_KEY,raw());const changed={...client.branch,raw:'foreign'};local.setItem(client.key,JSON.stringify(changed));assert.throws(()=>client.storage().getItem(SAVE_KEY));assert.throws(()=>client.storage().setItem(SAVE_KEY,raw()));assert.equal(JSON.parse(local.getItem(client.key)).raw,'foreign');});
test('MANUAL-017 interrupted choice reload stays frozen through restart without retroactive offline credit',async()=>{const before=globalThis.fetch;try{const db=new D1();await call(db,'/api/save',op());wiring(db);const local=new MemoryStorage(),client=new ManualSync(user,local);client.storage().setItem(SAVE_KEY,raw());let finish;client.onChoice=()=>new Promise(r=>finish=r);const waiting=client.sync();while(!finish)await new Promise(r=>setImmediate(r));assert.equal(client.branch.frozen,true);const old=decode(client.branch.raw).envelope;const recovered=new ManualSync(user,local);const fresh=decode(recovered.branch.raw).envelope;assert.deepEqual(fresh.state,old.state);assert.ok(fresh.savedAt>Date.now()-2000);finish('cancel');await waiting;}finally{globalThis.fetch=before;}});

test('MANUAL-018 definitive rejected upload can be corrected or downloaded on the next click',async()=>{const before=globalThis.fetch;try{const db=new D1(),client=new ManualSync(user,new MemoryStorage());wiring(db);const future=JSON.parse(raw());future.savedAt=Date.now()+99999999;client.storage().setItem(SAVE_KEY,JSON.stringify(future));await client.sync();assert.equal(client.branch.pending,null);assert.equal((await call(db,'/api/save')).revision,0);client.storage().setItem(SAVE_KEY,raw());await client.sync();assert.equal(client.branch.baseRevision,1);client.onChoice=async()=> 'download';await client.sync('download');assert.equal(client.branch.pending,null);}finally{globalThis.fetch=before;}});
