import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {registerHooks} from 'node:module';
registerHooks({resolve(s,c,next){try{return next(s,c);}catch(e){if(s.startsWith('.')&&!/\.[a-z]+$/i.test(s))return next(s+'.ts',c);throw e;}}});
const {createInitialState,createEngine,STEP_SECONDS}=await import('../src/slice/core/engine.ts');
const {addFurniture,validateLayoutState,interactionPoint}=await import('../src/slice/core/layout.ts');
const {validateState,createMemoryStorage,LocalSaveRepository}=await import('../src/slice/core/persistence.ts');
const {createPortableSave,parsePortableSave,overviewOf}=await import('../src/slice/core/portableSave.ts');
// Generated by the pre-fix v10 engine at t=34.8s with synthetic replenished stock.
// No user save, browser storage, identity or cloud data is used.
const checkpoint=JSON.parse(readFileSync(new URL('./fixtures/entry-counter-assignment-v9.json',import.meta.url),'utf8'));
const copy=v=>structuredClone(v);
const waiting=e=>e.state.customers.find(c=>c.id===6);
const business=s=>{s=copy(s);delete s.lastOfflineClaimId;delete s.offlineClaimIds;return s;};
function invariants(s){
 assert.equal(validateLayoutState(s),null);
 const unpaid=s.customers.filter(c=>['entering','queue','serving','receiving'].includes(c.phase));
 assert.equal(new Set(unpaid.map(c=>c.counterId)).size,unpaid.length);
 assert.equal(s.wallet+s.spend,1200+s.totalEarned);
}
function until(e,done,seconds=60){for(let i=0;i<seconds/STEP_SECONDS;i++){if(done())return;e.advance(STEP_SECONDS);invariants(e.state);}assert.fail('customer did not progress within synthetic bound');}
test('ENTRY-001 valid v10 outside waiter takes an available route on the next tick without another arrival or receipt',()=>{
 assert.equal(validateState(checkpoint).ok,true);
 const e=createEngine(checkpoint),before=e.snapshot(),others=copy(before.customers.filter(c=>c.id!==6));
 e.advance(STEP_SECONDS);
 assert.equal(waiting(e).counterId,'counter-a'); assert.equal(waiting(e).x,-7.875); assert.equal(waiting(e).z,5);
 assert.ok(waiting(e).nav.length); assert.deepEqual(waiting(e).nav.at(-1),{x:0,z:2});
 assert.equal(e.state.nextCustomerId,before.nextCustomerId); assert.equal(e.state.wallet,before.wallet); assert.equal(e.state.totalServed,before.totalServed);
 assert.deepEqual(e.state.ingredients,before.ingredients); assert.deepEqual(e.state.counters,before.counters);
 for(const old of others){const next=e.state.customers.find(c=>c.id===old.id);assert.equal(next.counterId,old.counterId);assert.ok(Math.hypot(next.x-old.x,next.z-old.z)<=.125+1e-9);}
 invariants(e.state);
});
test('ENTRY-002 reachable preferred counter stays preferred, while occupied orders are never double-booked',()=>{
 const seed=createInitialState();seed.nextCustomerId=2;seed.customers=[{id:1,x:-8,z:5,phase:'entering',counterId:'counter-b',timer:0,hasCup:false,skin:0}];
 const e=createEngine(seed);e.advance(STEP_SECONDS);assert.equal(e.state.customers[0].counterId,'counter-b');assert.equal(e.state.customers[0].x,-7.875);invariants(e.state);
 const busy=copy(checkpoint);busy.customers.push({id:7,x:0,z:2,phase:'queue',counterId:'counter-a',timer:0,hasCup:false,skin:0});busy.nextCustomerId=8;
 const blocked=createEngine(busy);blocked.advance(STEP_SECONDS);assert.equal(waiting(blocked).counterId,'counter-b');assert.equal(waiting(blocked).x,-8);assert.equal(waiting(blocked).nav,undefined);invariants(blocked.state);
 until(blocked,()=>waiting(blocked)?.nav!==undefined||!waiting(blocked));
});
test('ENTRY-003 a stocked alternate serves the guest after the assigned recipe runs out, with exact ingredient/payment accounting',()=>{
 const seed=copy(checkpoint);seed.paused=true;seed.ingredients={beans:10,milk:0};const e=createEngine(seed),before=e.snapshot();
 until(e,()=>!waiting(e));
 assert.equal(e.state.totalServed,before.totalServed+1);assert.equal(e.state.wallet,before.wallet+110);
 assert.deepEqual(e.state.ingredients,{beans:9,milk:0});assert.equal(e.state.counters[0].brewed,before.counters[0].brewed+1);
 assert.equal(e.state.counters[1].brewed,before.counters[1].brewed);invariants(e.state);
});
test('ENTRY-004 zero stock retains the safe drain path; paused renovation drains without money or stranded waiters',()=>{
 const seed=copy(checkpoint);seed.paused=true;seed.ingredients={beans:0,milk:0};const e=createEngine(seed),before=e.snapshot();
 assert.equal(e.beginLayoutEdit(),true);assert.equal(e.layoutEditStatus(),'draining');
 until(e,()=>e.layoutEditStatus()==='ready');assert.equal(e.state.customers.length,0);
 assert.equal(e.state.wallet,before.wallet);assert.equal(e.state.totalEarned,before.totalEarned);assert.equal(e.state.totalServed,before.totalServed);
 e.cancelLayoutEdit();assert.equal(e.state.paused,true);
});
test('ENTRY-005 recipe changes are reevaluated outside; an already reserved ingress route is never retargeted',()=>{
 const seed=copy(checkpoint);seed.paused=true;seed.ingredients={beans:10,milk:0};const e=createEngine(seed);
 e.setRecipe('counter-a','latte');e.advance(STEP_SECONDS);assert.equal(waiting(e).x,-8);assert.equal(waiting(e).counterId,'counter-b');
 e.setRecipe('counter-a','espresso');e.advance(STEP_SECONDS);assert.equal(waiting(e).counterId,'counter-a');assert.ok(waiting(e).nav);
 const destination=copy(waiting(e).nav.at(-1));e.setRecipe('counter-a','latte');
 e.advance(STEP_SECONDS);assert.equal(waiting(e).counterId,'counter-a');assert.deepEqual(waiting(e).nav.at(-1),destination);invariants(e.state);
 until(e,()=>!waiting(e));assert.equal(e.state.wallet,seed.wallet,'out-of-stock unstarted order never pays');
});
test('ENTRY-006 dynamic counters participate in cyclic fallback while stored instances are ignored',()=>{
 const s=createInitialState();s.wallet+=100000;s.totalEarned+=100000;s.totalServed=40;s.counters[0].brewed=40;s.paused=true;
 const e=createEngine(s);e.beginLayoutEdit();const d=e.createLayoutDraft();d.expanded=true;
 addFurniture(d,'counter',12,0);addFurniture(d,'counter',13,6);addFurniture(d,'counter',-4,3).stored=true;
 assert.equal(e.commitLayout(d).ok,true);const seed=e.snapshot();
 const counter=seed.counters.find(c=>c.id==='counter-c');counter.brewed++;seed.totalServed++;seed.totalEarned+=110;seed.wallet+=110;
 seed.customers=[{id:1,...interactionPoint(seed.layout.furniture.find(i=>i.id==='counter-c'),'service'),phase:'leaving',counterId:'counter-c',timer:0,hasCup:true,skin:0},{id:2,x:-8,z:5,phase:'entering',counterId:'counter-c',timer:0,hasCup:false,skin:1}];seed.nextCustomerId=3;
 const resumed=createEngine(seed);resumed.advance(STEP_SECONDS);const entrant=resumed.state.customers.find(c=>c.id===2);
 assert.ok(entrant.nav);assert.equal(entrant.counterId,'counter-d','fallback continues after the original counter, not always at A');
 assert.notEqual(entrant.counterId,'counter-5');invariants(resumed.state);
});
test('ENTRY-007 save, portable import, split steps and exact80% offline resume share the same routing and cannot double-credit',async()=>{
 const memory=createMemoryStorage(),repo=new LocalSaveRepository(memory);repo.load(100000);assert.equal(repo.save(checkpoint,100000).ok,true);
 const restored=new LocalSaveRepository(memory).load(100000).state;assert.deepEqual(restored,checkpoint);
 const portable=await createPortableSave({gameSchemaVersion:1,economyVersion:9,offlinePolicyVersion:4,saveId:'synthetic-entry-checkpoint',revision:1,savedAt:100000,exportedAt:100000,overview:overviewOf(checkpoint),state:checkpoint});
 const parsed=await parsePortableSave(portable.text);assert.equal(parsed.ok,true);
 const one=createEngine(checkpoint),split=createEngine(restored),offline=createEngine(parsed.file.payload.state);
 one.advance(48);for(let i=0;i<480;i++)split.advance(.1);assert.deepEqual(one.snapshot(),split.snapshot());
 assert.equal(offline.applyOffline(60,'entry-routing-once').accepted,true);assert.deepEqual(business(offline.snapshot()),business(one.snapshot()));
 const before=offline.snapshot();assert.equal(offline.applyOffline(60,'entry-routing-once').accepted,false);assert.deepEqual(offline.snapshot(),before);
 const reload=createEngine(split.snapshot());reload.advance(12);split.advance(12);assert.deepEqual(reload.snapshot(),split.snapshot());invariants(reload.state);
});
test('ENTRY-008 repeated admissions progress at both recipes without starvation, overlap or excess receipts',()=>{
 const e=createEngine();const counts=new Map(),spawned=new Set();let served=0;
 for(let i=0;i<6000;i++){
  e.state.ingredients={beans:120,milk:80};e.advance(STEP_SECONDS);invariants(e.state);
  for(const c of e.state.customers)spawned.add(c.id);
  for(const event of e.drainEvents())if(event.type==='served'){served++;counts.set(event.counterId,(counts.get(event.counterId)??0)+1);}
 }
 assert.ok(counts.get('counter-a')>10);assert.ok(counts.get('counter-b')>10);assert.equal(served,e.state.totalServed);assert.ok(served<=spawned.size);
 e.togglePause();until(e,()=>!e.state.customers.length);assert.equal(e.state.paused,true);
});
