import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';
registerHooks({resolve(s,c,next){try{return next(s,c);}catch(e){if(s.startsWith('.')&&!/\.[a-z]+$/i.test(s))return next(s+'.ts',c);throw e;}}});
const {createEngine,createInitialState}=await import('../src/slice/core/engine.ts');
const {ingredientCapacity}=await import('../src/slice/core/ingredients.ts');
const {layoutBounds,expansionSteps,expandLayout,addFurniture,moveFurniture,validateLayout,layoutExit}=await import('../src/slice/core/layout.ts');
const {validateState,LocalSaveRepository,createMemoryStorage,SAVE_KEY}=await import('../src/slice/core/persistence.ts');
const {createPortableSave,parsePortableSave,overviewOf}=await import('../src/slice/core/portableSave.ts');
const {furnitureInventory}=await import('../src/slice/core/furnitureCatalog.ts');
function funded(){const s=createInitialState();s.wallet+=100000;s.totalEarned+=100000;return createEngine(s);}
function dining(){const e=funded();e.togglePause();e.beginLayoutEdit();const d=e.createLayoutDraft();addFurniture(d,'table',-4,3);assert.equal(e.commitLayout(d).ok,true);e.togglePause();for(let i=0;i<4000&&!e.state.customers.some(c=>c.phase==='dining');i++)e.advance(.05);const customer=e.state.customers.find(c=>c.phase==='dining');assert.ok(customer);e.state.customers=[customer];e.state.counters.forEach((c,i)=>{c.brew=null;c.brewed=i?0:e.state.totalServed;});e.state.paused=true;customer.timer=0;e.state.ingredients={beans:0,milk:0};e.drainEvents();assert.equal(validateState(e.snapshot()).ok,true);return e;}
function save(state,at=100000){const store=createMemoryStorage(),repo=new LocalSaveRepository(store);repo.load(at);assert.equal(repo.save(state,at).ok,true);return{store,repo};}
test('GROW-001 warehouse levels change capacity only, charge once and obey max/funds guards',()=>{const e=funded(),stock={...e.state.ingredients};let paid=0;for(let level=1;level<=5;level++){assert.equal(e.warehouseQuote().level,level);assert.equal(e.ingredientQuote('beans','fill').capacity,120+(level-1)*60);assert.equal(e.ingredientQuote('milk','fill').capacity,80+(level-1)*40);if(level<5){paid+=1200*level;assert.equal(e.upgradeWarehouse(),true);assert.deepEqual(e.state.ingredients,stock);assert.equal(e.state.spend,paid);assert.equal(validateState(e.snapshot()).ok,true);}}const final=e.snapshot();assert.equal(e.upgradeWarehouse(),false);assert.deepEqual(e.snapshot(),final);const poor=createEngine();poor.state.wallet=0;poor.state.spend=1200;assert.equal(poor.upgradeWarehouse(),false);});
test('GROW-002 upgraded fill/cap validation and v8 portable preserve all growth fields',async()=>{const e=funded();e.upgradeWarehouse();assert.equal(e.buyIngredient('beans','fill'),true);assert.equal(e.state.ingredients.beans,180);const bad=e.snapshot();bad.ingredients.beans=181;assert.equal(validateState(bad).ok,false);for(const level of [0,1.5,6,null]){const s=e.snapshot();s.warehouseLevel=level;assert.equal(validateState(s).ok,false);}const {repo}=save(e.snapshot());const env=repo.durableSnapshot();const f=await createPortableSave({gameSchemaVersion:1,economyVersion:9,offlinePolicyVersion:4,saveId:env.saveId,revision:env.revision,savedAt:env.savedAt,exportedAt:env.savedAt,overview:overviewOf(env.state),state:env.state});const p=await parsePortableSave(f.text);assert.equal(p.ok,true);assert.equal(p.file.payload.state.warehouseLevel,2);assert.equal(p.file.payload.state.ingredients.beans,180);});
test('GROW-003 every width/depth combination commits exact cost and permits far-edge furniture/routes',()=>{for(let w=0;w<=3;w++)for(let d=0;d<=3;d++){const e=funded();e.state.totalServed=40;e.state.counters[0].brewed=40;e.togglePause();e.beginLayoutEdit();const draft=e.createLayoutDraft();for(let i=0;i<w;i++)assert.equal(expandLayout(draft,'width'),true);for(let i=0;i<d;i++)assert.equal(expandLayout(draft,'depth'),true);const b=layoutBounds(draft);assert.deepEqual([b.width,b.depth],[18+6*w,13+4*d]);moveFurniture(draft,'counter-b',b.maxX-2,b.maxZ-(d?2:5));assert.equal(validateLayout(draft).ok,true);assert.equal(e.state.spend,0);assert.equal(e.commitLayout(draft).ok,true);assert.equal(e.state.spend,(w+d)*6000);assert.equal(validateState(e.snapshot()).ok,true);assert.equal(layoutExit(e.state.layout).x,b.maxX+1);e.togglePause();e.advance(120);assert.equal(validateState(e.snapshot()).ok,true);}});
test('GROW-004 draft cancellation is free, paid dimensions cannot shrink and axis caps are independent',()=>{const e=funded();e.state.totalServed=40;e.state.counters[0].brewed=40;e.togglePause();const before=e.snapshot();e.beginLayoutEdit();const d=e.createLayoutDraft();for(let i=0;i<3;i++)expandLayout(d,'depth');assert.equal(expandLayout(d,'depth'),false);assert.equal(expandLayout(d,'width'),true);e.cancelLayoutEdit();assert.deepEqual(e.snapshot(),before);e.beginLayoutEdit();assert.equal(e.commitLayout(d).ok,true);const paid=e.state.spend;e.beginLayoutEdit();const shrink=e.createLayoutDraft();shrink.depthSteps=2;assert.equal(e.commitLayout(shrink).ok,false);assert.equal(e.state.spend,paid);});
test('GROW-005 seat levels belong to owned instances; draft cannot mint/erase levels',()=>{const e=funded();e.togglePause();e.beginLayoutEdit();let d=e.createLayoutDraft();const a=addFurniture(d,'table',-4,3),b=addFurniture(d,'table',4,5);a.stored=b.stored=true;assert.equal(e.commitLayout(d).ok,true);const wallet=e.state.wallet;assert.equal(e.upgradeSeat(a.id),true);assert.equal(e.state.wallet,wallet-400);assert.equal(e.seatQuote(a.id).tip,20);assert.equal(e.seatQuote(b.id).tip,10);assert.equal(furnitureInventory(e.state,e.state.layout,'table').needsChoice,true);assert.equal(validateState(e.snapshot()).ok,true);e.beginLayoutEdit();d=e.createLayoutDraft();d.furniture.find(x=>x.id===a.id).level=3;assert.equal(e.commitLayout(d).ok,false);d=e.createLayoutDraft();addFurniture(d,'table',5,5).level=10;assert.equal(e.commitLayout(d).ok,false);e.cancelLayoutEdit();const {store}=save(e.snapshot());const loaded=new LocalSaveRepository(store).load(100000);assert.equal(loaded.state.layout.furniture.find(x=>x.id===a.id).level,2);});
test('TIP-001 seating snapshots a tip, upgrade preserves it, completion credits exactly once',()=>{const e=dining(),c=e.state.customers[0],table=c.seatId;assert.equal(c.tipDue,10);assert.equal(e.upgradeSeat(table),true);assert.equal(c.tipDue,10);const wallet=e.state.wallet,earned=e.state.totalEarned,served=e.state.totalServed;e.advance(5.95);assert.equal(e.state.wallet,wallet);e.advance(.05);assert.equal(e.state.wallet,wallet+10);assert.equal(e.state.totalEarned,earned+10);assert.equal(e.state.totalServed,served);assert.equal(c.tipDue,undefined);assert.equal(c.phase,'leaving');assert.equal(e.drainEvents().filter(x=>x.type==='tipped').length,1);e.advance(30);assert.equal(e.state.wallet,wallet+10);assert.equal(validateState(e.snapshot()).ok,true);});
test('TIP-002 offline settlement and save/reload boundaries cannot pay a diner twice',()=>{const e=dining();e.state.paused=false;const initial=e.snapshot(),wallet=initial.wallet;const {store}=save(initial);const once=new LocalSaveRepository(store).load(107500);assert.equal(once.state.wallet,wallet+10);assert.equal(new LocalSaveRepository(store).load(107500).state.wallet,wallet+10);const replay=createEngine(initial);replay.applyOffline(7.5,'one');const paid=replay.state.wallet;assert.equal(replay.applyOffline(7.5,'one').accepted,false);assert.equal(replay.state.wallet,paid);});
test('TIP-003 legacy v7 diners get no invented tip, migration is idempotent and new fields cannot relabel old files',()=>{const e=dining(),old=e.snapshot();old.economyVersion=7;delete old.customers[0].tipDue;const wallet=old.wallet;const migrated=validateState(old);assert.equal(migrated.ok,true);assert.equal(migrated.state.customers[0].tipDue,0);assert.equal(migrated.state.wallet,wallet);assert.deepEqual(validateState(migrated.state).state,migrated.state);const restored=createEngine(migrated.state);restored.advance(10);assert.equal(restored.state.wallet,wallet);for(const mutate of [s=>s.layout.depthSteps=1,s=>s.layout.furniture.find(x=>x.kind==='table').level=2,s=>s.customers[0].tipDue=10]){const s=structuredClone(old);mutate(s);assert.equal(validateState(s).ok,false);}const noTip=e.snapshot();delete noTip.customers[0].tipDue;assert.equal(validateState(noTip).ok,false);});

test('GROW-006 explicit malformed optional level/step fields fail instead of defaulting',()=>{for(const field of ['widthSteps','depthSteps'])for(const value of [null,-1,4,1.5,'1']){const state=createInitialState();state.layout[field]=value;assert.equal(validateState(state).ok,false,field+':'+value);}const e=dining();e.state.layout.furniture.find(x=>x.kind==='table').level=null;assert.equal(validateState(e.snapshot()).ok,false);});

test('TIP-004 tip snapshot cannot exceed its owned seat level but old smaller quotes survive upgrades',()=>{const e=dining(),s=e.snapshot();s.customers[0].tipDue=100;assert.equal(validateState(s).ok,false);e.upgradeSeat(e.state.customers[0].seatId);assert.equal(validateState(e.snapshot()).ok,true);});
