import test from 'node:test';import assert from 'node:assert/strict';import {registerHooks} from 'node:module';
registerHooks({resolve(s,c,next){try{return next(s,c);}catch(e){if(s.startsWith('.')&&!/\.[a-z]+$/i.test(s))return next(s+'.ts',c);throw e;}}});
const {createEngine,createInitialState}=await import('../src/slice/core/engine.ts');
const {addFurniture,moveFurniture,storeFurniture,moveFurnitureGroup,validateLayout,layoutCost}=await import('../src/slice/core/layout.ts');
const {isCounterId,counterOrdinal,compareCounterIds}=await import('../src/slice/core/furnitureIds.ts');
const {furnitureInventory}=await import('../src/slice/core/furnitureCatalog.ts');
const {validateState,createMemoryStorage,LocalSaveRepository,SAVE_KEY}=await import('../src/slice/core/persistence.ts');
const {createPortableSave,parsePortableSave,overviewOf}=await import('../src/slice/core/portableSave.ts');
function shop(){const s=createInitialState();s.wallet+=10000000;s.totalEarned+=10000000;s.paused=true;return createEngine(s);}
function snapshotFile(s){return createPortableSave({gameSchemaVersion:1,economyVersion:9,offlinePolicyVersion:4,saveId:'synthetic-stock-file',revision:1,savedAt:100000,exportedAt:100000,overview:overviewOf(s),state:s});}
test('UNLIMITED-001 many stored instances have stable canonical IDs beyond 9/10/100 and round-trip',async()=>{const e=shop();e.beginLayoutEdit();const d=e.createLayoutDraft();for(let i=0;i<110;i++)addFurniture(d,'counter',-4,3).stored=true;for(let i=0;i<40;i++)addFurniture(d,'table',-4,3).stored=true;assert.equal(new Set(d.furniture.map(x=>x.id)).size,d.furniture.length);assert.equal(e.commitLayout(d).ok,true);assert.ok(e.state.counters.some(x=>x.id==='counter-100'));assert.ok(e.state.counters.findIndex(x=>x.id==='counter-9')<e.state.counters.findIndex(x=>x.id==='counter-10'));assert.equal(e.upgrade('counter-5'),true);assert.equal(e.setRecipe('counter-5','latte'),true);assert.equal(e.upgradeSeat('table-17'),true);assert.equal(validateState(e.snapshot()).ok,true);const memory=createMemoryStorage(),repo=new LocalSaveRepository(memory);repo.load(100000);assert.equal(repo.save(e.snapshot(),100000).ok,true);assert.deepEqual(new LocalSaveRepository(memory).load(100000).state,e.snapshot());const parsed=await parsePortableSave((await snapshotFile(e.snapshot())).text);assert.equal(parsed.ok,true);assert.deepEqual(parsed.file.payload.state,e.snapshot());assert.equal(furnitureInventory(e.state,e.state.layout,'counter').choices.length,2);});
test('UNLIMITED-002 fifth placed counter operates and thirteenth table fits when paths/space permit',()=>{const e=shop();e.state.totalServed=40;e.state.counters[0].brewed=40;e.beginLayoutEdit();const d=e.createLayoutDraft();d.expanded=true;d.widthSteps=3;d.depthSteps=3;for(const [x,z]of[[-3,9],[5,9],[13,9]])addFurniture(d,'counter',x,z);for(let i=0;i<15;i++)addFurniture(d,'table',-5+(i%5)*4,14+Math.floor(i/5)*2);assert.equal(validateLayout(d).ok,true);assert.equal(e.commitLayout(d).ok,true);assert.equal(e.state.counters.length,5);assert.equal(e.state.layout.furniture.filter(x=>x.kind==='table'&&!x.stored).length,15);assert.equal(e.setRecipe('counter-5','espresso'),false);e.togglePause();e.advance(120);assert.ok(e.state.counters.find(x=>x.id==='counter-5').brewed>0);assert.equal(validateState(e.snapshot()).ok,true);});
test('UNLIMITED-003 inventory export uses byte protection rather than an old furniture-node count',async()=>{const e=shop();e.beginLayoutEdit();const d=e.createLayoutDraft();for(let i=0;i<1500;i++)addFurniture(d,'table',-4,3).stored=true;assert.equal(e.commitLayout(d).ok,true);const f=await snapshotFile(e.snapshot());assert.equal((await parsePortableSave(f.text)).ok,true);assert.equal(furnitureInventory(e.state,e.state.layout,'table').choices.length,1);});
test('UNLIMITED-004 malformed IDs/duplicates fail; old v8 assets remain identical',()=>{for(const id of ['counter-0','counter-4','counter-05','counter-x','counter-9007199254740992'])assert.equal(isCounterId(id),false,id);for(const id of ['counter-a','counter-d','counter-5','counter-10','counter-100'])assert.equal(isCounterId(id),true,id);assert.equal(counterOrdinal('counter-a'),1);assert.ok(compareCounterIds('counter-9','counter-10')<0);const e=shop();e.beginLayoutEdit();const d=e.createLayoutDraft();addFurniture(d,'counter',-4,3).stored=true;assert.equal(e.commitLayout(d).ok,true);const old=e.snapshot();old.economyVersion=8;assert.deepEqual(validateState(old).state,{...old,economyVersion:9});const bad=e.snapshot();bad.counters.push({...bad.counters[0]});assert.equal(validateState(bad).ok,false);});
test('GROUP-001 rigid translation is detached, costs zero and preserves all instance fields',()=>{const e=shop();e.upgrade('counter-a');e.beginLayoutEdit();const source=e.createLayoutDraft(),before=structuredClone(source);const result=moveFurnitureGroup(source,['counter-a','counter-b'],1,2);assert.equal(result.ok,true);assert.deepEqual(source,before);for(const id of ['counter-a','counter-b']){const old=source.furniture.find(x=>x.id===id),moved=result.layout.furniture.find(x=>x.id===id);assert.deepEqual(moved,{...old,x:old.x+1,z:old.z+2});}assert.equal(layoutCost(e.state,result.layout).cost,0);const wallet=e.state.wallet;assert.equal(e.commitLayout(result.layout).ok,true);assert.equal(e.state.wallet,wallet);assert.equal(e.state.counters.find(x=>x.id==='counter-a').level,2);});
test('GROUP-002 whole group rejects overlap/bounds/ports and never mutates its source',()=>{const e=shop();e.beginLayoutEdit();const source=e.createLayoutDraft();addFurniture(source,'table',-4,3);const original=structuredClone(source);for(const [ids,dx,dz]of[[['counter-a','counter-b'],100,0],[['counter-a','table-1'],5,0],[['counter-a','counter-b'],0,-3],[['counter-a','missing'],1,0],[['counter-a','counter-a'],1,0]]){assert.equal(moveFurnitureGroup(source,ids,dx,dz).ok,false);assert.deepEqual(source,original);}storeFurniture(source,'table-1');assert.equal(moveFurnitureGroup(source,['counter-a','table-1'],1,0).ok,false);});

test('UNLIMITED-005 v8 malformed counter gaps remain rejected while genuine assets migrate',()=>{const e=shop();e.beginLayoutEdit();const d=e.createLayoutDraft();addFurniture(d,'counter',-4,3).stored=true;e.commitLayout(d);const s=e.snapshot();s.economyVersion=8;s.counters[2].id='counter-d';const f=s.layout.furniture.find(x=>x.id==='counter-c');f.id=f.counterId='counter-d';assert.equal(validateState(s).ok,false);});
